/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminPanelRouteRouteImport } from './routes/admin/_panel/route'
import { Route as AdminPanelProjectsRouteImport } from './routes/admin/_panel/projects'
import { Route as AdminPanelProfileRouteImport } from './routes/admin/_panel/profile'
import { Route as AdminPanelExperienceRouteImport } from './routes/admin/_panel/experience'
import { Route as AdminPanelEducationRouteImport } from './routes/admin/_panel/education'
import { Route as AdminPanelAboutRouteImport } from './routes/admin/_panel/about'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPanelRouteRoute = AdminPanelRouteRouteImport.update({
  id: '/admin/_panel',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelProjectsRoute = AdminPanelProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminPanelRouteRoute,
} as any)
const AdminPanelProfileRoute = AdminPanelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminPanelRouteRoute,
} as any)
const AdminPanelExperienceRoute = AdminPanelExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminPanelRouteRoute,
} as any)
const AdminPanelEducationRoute = AdminPanelEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AdminPanelRouteRoute,
} as any)
const AdminPanelAboutRoute = AdminPanelAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminPanelRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminPanelRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/about': typeof AdminPanelAboutRoute
  '/admin/education': typeof AdminPanelEducationRoute
  '/admin/experience': typeof AdminPanelExperienceRoute
  '/admin/profile': typeof AdminPanelProfileRoute
  '/admin/projects': typeof AdminPanelProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/about': typeof AdminPanelAboutRoute
  '/admin/education': typeof AdminPanelEducationRoute
  '/admin/experience': typeof AdminPanelExperienceRoute
  '/admin/profile': typeof AdminPanelProfileRoute
  '/admin/projects': typeof AdminPanelProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/_panel': typeof AdminPanelRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/_panel/about': typeof AdminPanelAboutRoute
  '/admin/_panel/education': typeof AdminPanelEducationRoute
  '/admin/_panel/experience': typeof AdminPanelExperienceRoute
  '/admin/_panel/profile': typeof AdminPanelProfileRoute
  '/admin/_panel/projects': typeof AdminPanelProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/about'
    | '/admin/education'
    | '/admin/experience'
    | '/admin/profile'
    | '/admin/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/reset-password'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/about'
    | '/admin/education'
    | '/admin/experience'
    | '/admin/profile'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/reset-password'
    | '/admin/_panel'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/_panel/about'
    | '/admin/_panel/education'
    | '/admin/_panel/experience'
    | '/admin/_panel/profile'
    | '/admin/_panel/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminPanelRouteRoute: typeof AdminPanelRouteRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel': {
      id: '/admin/_panel'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_panel/projects': {
      id: '/admin/_panel/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminPanelProjectsRouteImport
      parentRoute: typeof AdminPanelRouteRoute
    }
    '/admin/_panel/profile': {
      id: '/admin/_panel/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminPanelProfileRouteImport
      parentRoute: typeof AdminPanelRouteRoute
    }
    '/admin/_panel/experience': {
      id: '/admin/_panel/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminPanelExperienceRouteImport
      parentRoute: typeof AdminPanelRouteRoute
    }
    '/admin/_panel/education': {
      id: '/admin/_panel/education'
      path: '/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminPanelEducationRouteImport
      parentRoute: typeof AdminPanelRouteRoute
    }
    '/admin/_panel/about': {
      id: '/admin/_panel/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminPanelAboutRouteImport
      parentRoute: typeof AdminPanelRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPanelRouteRouteChildren {
  AdminPanelAboutRoute: typeof AdminPanelAboutRoute
  AdminPanelEducationRoute: typeof AdminPanelEducationRoute
  AdminPanelExperienceRoute: typeof AdminPanelExperienceRoute
  AdminPanelProfileRoute: typeof AdminPanelProfileRoute
  AdminPanelProjectsRoute: typeof AdminPanelProjectsRoute
}

const AdminPanelRouteRouteChildren: AdminPanelRouteRouteChildren = {
  AdminPanelAboutRoute: AdminPanelAboutRoute,
  AdminPanelEducationRoute: AdminPanelEducationRoute,
  AdminPanelExperienceRoute: AdminPanelExperienceRoute,
  AdminPanelProfileRoute: AdminPanelProfileRoute,
  AdminPanelProjectsRoute: AdminPanelProjectsRoute,
}

const AdminPanelRouteRouteWithChildren = AdminPanelRouteRoute._addFileChildren(
  AdminPanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminPanelRouteRoute: AdminPanelRouteRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
